version: '3'
services:
  flask:
    image: stitcher
    container_name: flask
    build: .
    environment:
      - FLASK_DEBUG=1
    networks:
      my-network:
        aliases:
          - flask-app
    expose:
      - 3000
          
  nginx:
    image: nginx:1.13.7
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    depends_on:
      - flask

networks:
  my-network: